//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonovalovArtemUpISP41.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> Doljnost { get; set; }
        public Nullable<int> Pol { get; set; }
        public string Foto { get; set; }
        public string SecretWord { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual DoljnostList DoljnostList { get; set; }
        public virtual PolList PolList { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
